apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::536864977932:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-QZFHORIMT9PA
      username: system:node:{{EC2PrivateDNSName}}
    -groups:
      - system:masters
      rolearn: arn:aws:iam::536864977932:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-09T00:01:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1614"
  uid: 70f47867-2d99-4fd3-8e8b-a8b3a3fb809f
