apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::536864977932:role/eksctl-simple-jwt-api-cluster-ServiceRole-1Q3MCTDYXOLKI
      username: system.node:{{EC2PrivateDNSName}}
    - groups:
      - system:master
      rolearn: arn:aws:iam::536864977932:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-09T20:18:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "84952"
  uid: 5b18015d-b834-4fd2-8220-58104022f5f0
