apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-jwt-api-deployment
  labels:
    app: simple-jwt-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-jwt-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: simple-jwt-api
    spec:
      containers:
      - name: simple-jwt-api
        image: sunday0prime/simple-jwt-api
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
        ports:
          - containerPort: 8080
